USE [master]
GO

/****** Object:  Database [TRUserManagement]    Script Date: 15/06/2016 23:03:03 ******/
DROP DATABASE [TRUserManagement]
GO

/****** Object:  Database [TRUserManagement]    Script Date: 15/06/2016 23:03:03 ******/
CREATE DATABASE [TRUserManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TRUserManagement', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TRUserManagement.mdf' , SIZE = 14336KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TRUserManagement_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TRUserManagement_log.ldf' , SIZE = 92864KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TRUserManagement] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TRUserManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TRUserManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TRUserManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TRUserManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TRUserManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TRUserManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [TRUserManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TRUserManagement] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TRUserManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TRUserManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TRUserManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TRUserManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TRUserManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TRUserManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TRUserManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TRUserManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TRUserManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TRUserManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TRUserManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TRUserManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TRUserManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TRUserManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TRUserManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TRUserManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TRUserManagement] SET RECOVERY FULL 
GO

ALTER DATABASE [TRUserManagement] SET  MULTI_USER 
GO

ALTER DATABASE [TRUserManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TRUserManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TRUserManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TRUserManagement] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TRUserManagement] SET  READ_WRITE 
GO


