DECLARE @Container VARCHAR(20) = 'Membership'

EXEC [membership].[PolicyUpdate] @Container = @Container, @Name = 'AccountLockedTimeout', @Enabled = 1, @Value = '5'
EXEC [membership].[PolicyUpdate] @Container = @Container, @Name = 'AccountLockout', @Enabled = 1, @Value = '3'
EXEC [membership].[PolicyUpdate] @Container = @Container, @Name = 'InactiveDisableDays', @Enabled = 1, @Value = '30'
EXEC [membership].[PolicyUpdate] @Container = @Container, @Name = 'PasswordExpiry', @Enabled = 1, @Value = '30'
EXEC [membership].[PolicyUpdate] @Container = @Container, @Name = 'PasswordHistory', @Enabled = 1, @Value = '10'
EXEC [membership].[PolicyUpdate] @Container = @Container, @Name = 'PasswordLength', @Enabled = 1, @Value = '8'
EXEC [membership].[PolicyUpdate] @Container = @Container, @Name = 'PasswordLowerChars', @Enabled = 1, @Value = '1'
EXEC [membership].[PolicyUpdate] @Container = @Container, @Name = 'PasswordNumericDigits', @Enabled = 1, @Value = '1'
EXEC [membership].[PolicyUpdate] @Container = @Container, @Name = 'PasswordUpperChars', @Enabled = 1, @Value = '1'

GO


/****** Script for SelectTopNRows command from SSMS  ******/
/************   Insert connection strings   **********/
INSERT INTO [traderiser].[ConnectionString] ([ConnectionName],[ConnectionString],[Provider])
     VALUES ('log-direct', 'Application Name=Logs;Data Source=CUDJOE-DEV;Database=TRUserManagement;Integrated Security=True;Pooling=True;Max Pool Size=100;Min Pool Size=0;Connection Lifetime=0;Connection Reset=True;Enlist=True', 'TradeRiser.Core.Data.SqlServerDatabaseProvider, TradeRiser.Core') 
INSERT INTO [traderiser].[ConnectionString] ([ConnectionName],[ConnectionString],[Provider])
     VALUES ('membership-direct', 'Application Name=Logs;Data Source=CUDJOE-DEV;Database=TRUserManagement;Integrated Security=True;Pooling=True;Max Pool Size=100;Min Pool Size=0;Connection Lifetime=0;Connection Reset=True;Enlist=True', 'TradeRiser.Core.Data.SqlServerDatabaseProvider, TradeRiser.Core') 


	 /*
	 SELECT 'INSERT INTO [traderiser].[ConnectionString] ([ConnectionName],[ConnectionString],[Provider])
     VALUES (''' + [ConnectionName] + ''', ''' + '',[ConnectionString]  + ''', ''' + '',[Provider] + ''') ' 
  FROM [TRUserManagement].[traderiser].[ConnectionString]
  */
	 /************   Insert configuration items   **********/

	 /*
	 SELECT 'INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
      VALUES ('''+[Name]+''','''+'',[DataType]+''','''+'',[Value]+''','''+'','1'') ' 
  FROM [TRUserManagement].[traderiser].[ConfigurationItem]
	 */

INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Cache.AdhocDelegatedUserCacheExpiryInMinutes','Int','30','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Cache.AdhocUserCacheExpiryInMinutes','Int','30','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Cache.AdhocUserInstancePermissionsCacheExpiryInMinutes','Int','30','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Cache.AdhocUserPermissionsCacheExpiryInMinutes','Int','30','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Cache.TempFileNumberOfDaysBeforeDeleting','Int','15','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.AjaxTimeout','Int','600000','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.ApplicationName','Text','TradeRiser','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.ApplicationVersion','Text','1.000000','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.Branding.Accent','Text','#007dbb','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.Branding.Chrome','Text','Light','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.Branding.Logo-Dark','Text','traderiser-logo-dark.png','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.Branding.Logo-Light','Text','traderiser-logo-light.png','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.Branding.Logo-Logon','Text','traderiser-logo-logon.png','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.Branding.PrintLogo','Text','print-logo.png','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.Branding.ProductName','Text','TradeRiser','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.Branding.Theme',' Text','Dark','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.ChangePasswordPageTitle','ResourceText','TradeRiser - Change Password','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.CookieExpiryHours','Int','48','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.CookiePath',' Text','/TradeRiser','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.CopyrightMessage','Text','© Copyright TradeRiser Ltd 2012 - {0}','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.DefaultExcelFormat',' Text','xls','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.DefaultLanguage','Text','en-US','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.DisabledApplications','Text','ThoughtFlow','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.Email.HTML-Footer','Text','','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.Email.HTML-Template','Text','<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.Email.LogoURL','Text','/images/traderiser.png','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EmailFromAddress','Text','traderiser@mydomain.com','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EmailFromDisplayName','Text','TradeRiser','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EmailIntegration','Bool','True','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EmailNewIntegratedUserTemplate','ResourceText','Welcome to TradeRiser.\n\nYour username is {USERNAME}\n\nYour account has been created with integrated security meaning you can use your Windows logon to gain access to the system when you access it here {LOGONURL}\n\nIf you have any queries contact the service department on {SERVICEPHONE}.', '1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EmailNewUserSubject','ResourceText','Welcome to TradeRiser','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EmailNewUserTemplate','ResourceText','Welcome to TradeRiser.\n\nYour username is {USERNAME}\n\nYour temporary password is {PASSWORD}\n\nYou will be asked to change your password when you first log on.  You can access the system here {LOGONURL}\n\nIf you have any queries contact the service department on {SERVICEPHONE}.' ,'1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EmailPasswordResetConfirmation','ResourceText','Your password has been successfully reset.\n\nYou can access the system here {LOGONURL}\n\nIf you did not request for your password to be reset, please contact your administrator.\n\nIf you have any queries contact the service department on {SERVICEPHONE}.' ,'1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EmailPasswordResetConfirmationSubject','ResourceText','Password Reset Success','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EmailReplyToAddress','Text','donotreply@mydomain.com','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EmailReplyToDisplayName',' Text','DoNotReply','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EmailResetPasswordSubject',' ResourceText','Reset Password','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EmailResetPasswordTemplate','ResourceText','You recently requested a password reset.\n\nClick the link below to change your password\n\n{RESETLINK}\n\nIf you did not request for your password to be reset or you no longer require it, please ignore this email.\n\nIf you have any queries contact the service department on {SERVICEPHONE}.', '1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EmailToken.{LOGONURL}','Text','http://CUDJOE-DEV/TradeRiser/core/logon','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EmailToken.{SERVICEPHONE}',' Text','+44 (0)79 495605248','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EnableLogOffPrompt','Bool','True','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EnableSecureCookie','Bool','False','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EncryptionKeyContainer','Text','Core.TradeRiser','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.ExcludedReturnUrls',' Text','[''core/logon'', ''core/logoff'', ''traderiser/reporting'']','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.ExternalApplicationAddress','Text','http://CUDJOE-DEV/TradeRiser','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.FullErrorDetails','Bool','False','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.HelpDeskContact','Text','+44 (0)20 7430 0715','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.ImageUploadSettings','Text','{''maxHeight'': ''800'', ''maxWidth'': ''800'', ''quality'': ''80''}','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.InstalledLanguages',' Text','en-GB;en-US;fr-CA;es-PR','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.InstallLocation','Text','C:\Program Files\TradeRiser','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.JSUtilityMethods','Text','function $IN(value, array) { var found = false; if (!array) { return false; } for (var i = 0; i < array.length; i++) { if (array[i] == value) { found = true; break; } } return found; }; function $DATE(value, days) { var dateObj; if (typeof (value) == ''undefined'' || value == null) { dateObj = new Date(); } else { dateObj = new Date(value); } if (typeof (days) != ''undefined'') { dateObj.setDate(dateObj.getDate() + (days - 0)); } return dateObj; }; function $TIME(value) { var date = new Date(''2012/09/20 '' + value); return date; }; function $DYNODATETIME(date) { var isNullOrEmpty = function (value) { if (value === null || value === undefined || value === '''') { return true; } return false; }; var newDate = null; if (isNullOrEmpty(TIMEOFFSET)) { TIMEOFFSET = DynoDateOffset(); } if (!isNullOrEmpty(date)) { newDate = new Date(date); } else { newDate = new Date(); } if (!isNullOrEmpty(TIMEOFFSET)) { var timeParts = TIMEOFFSET.split('':''); var sign = timeParts[0].substring(0, 1); var hours = timeParts[0].substring(1, 3); var mins = timeParts[1]; var secondsSplit = timeParts[2].split(''.''); var seconds = secondsSplit[0]; if (sign === ''+'') { newDate.setHours(newDate.getHours() - hours); newDate.setMinutes(newDate.getMinutes() - mins); newDate.setSeconds(newDate.getSeconds() - seconds); } if (sign === ''-'') { newDate.setHours(newDate.getHours() - -hours); newDate.setMinutes(newDate.getMinutes() - -mins); newDate.setSeconds(newDate.getSeconds() - -seconds); } } return newDate; }; function DynoUTCDate() { var now = new Date(); var now_utc = new Date(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate(), now.getUTCHours(), now.getUTCMinutes(), now.getUTCSeconds()); return now_utc; }; function DynoDateOffset() { var pad = function (number, count) { return Array(count - String(number).length + 1).join(''0'') + number; }; var now = new Date(); var utcDate = DynoUTCDate(); var differnce = (now - utcDate); var _hours = 1000 * 60 * 60; var _mins = 1000 * 60; var _sec = 1000; var hours = Math.floor(Math.abs(differnce / _hours)); var mins = Math.floor(Math.abs((differnce / _mins) % 60)); var secs = Math.floor(Math.abs((differnce / _sec) % 60)); var timespan = pad(hours, 2) + '':'' + pad(mins, 2) + '':'' + pad(secs, 2); if (now > utcDate) { timespan = ''+'' + timespan; } else { timespan = ''-'' + timespan; } return timespan; };','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.LegalHyperlinkUrl','Text','http://www.traderiser.com','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.LogOffPromptMinutes','Int','50','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.LogonDefaultAreaName','Text','core','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.LogonNewsVisible','Bool','True','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.LogonPageTitle',' Text','TradeRiser - Log on','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.LogOnTimeoutMinutes','Int','60','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.MemoryCacheManager.CacheMaintenancePeerTimeout','Int','30','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.MemoryCacheManager.CacheMaintenancePeerTimeoutRetry','Int','2','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.MemoryCacheManager.CacheMaintenanceUrlTemplate','Text','http://{0}/Secure4/MemoryCacheManager/Maintenance/{1}','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.MemoryCacheManager.ServerMemberList','Text','http://CUDJOE-DEV:8003/cache/purge?','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.MinResultsRequiredForBottomPager','Int','20','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.PasswordResetExpiryHours','int','24','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.PermissionsSubstringLength','int','150','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.PersistCookie','Bool','False','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.PrivacyHyperlinkUrl','Text','http://www.traderiser.com','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.SecurityMode','Text','Forms','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.ShowPasswordOnReset','Bool','True','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.SmtpAccount','Text','','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.SmtpPassword','Text','','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.SmtpPort','Int','25','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.SmtpServer',' Text','localhost','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.SmtpUseSsl','Bool','False','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.UploadsLocation',' Text','\\CUDJOE-DEV\Uploads','1') 
/*INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.VirtualDateTimes','Text','[{"label":"$RESX(''Sysrepublic.Secure.Core.Resources'', ''VirtualDate_Today'', ''Today'')","key":"today","startDateExp":"virtualDate.UserTimeStartOfToday()","endDateExp":"virtualDate.UserTimeEndOfToday()"},{"label":"$RESX(''Sysrepublic.Secure.Core.Resources'', ''Vi 1'') 
*/INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.ZipMaxAttachmentsWithSameDisplayNameCheck','Int','50','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('GoogleMap.ApiKey','Text','AIzaSyC1VsFf3LaxD9MEa-NW_INr9AXjHvVlnXE','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('HSO.Domain','Text','http://www.traderiser.com','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Logging.Core.LogTimeInterval',' Int','180000','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Repo.MaxRepoEntriesForSystem',' Int','1000000','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Repo.MaxRepoEntriesForUser','Int','100','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Repo.SystemRepoRoot','Text','\\CUDJOE-DEV\Repo','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Reporting.EnableIncidentChangeLogging','Bool','False','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Reporting.MaxChartPlotPoints',' int','255','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Search.DefaultMaxUserWorkspaceStorage','Int','100','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Search.DefaultOriginUrl',' Text','core/SearchResults/{container}/{name}','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Search.RestrictSsrCopies','Bool','false','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('SearchService.DefaultTTL','Text','00.00:30:00.00','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('SearchService.GarbageCollectOnRun','Bool','True','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('SearchService.MaximumCacheAge','Text','00.01:00:00.00','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('SearchService.ResultsReader.CachedResultsRootFolder','Text','\\CUDJOE-DEV\Workspaces','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('SearchService.ResultsReader.FetchResultsIORetryCycles','Int','5','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('SearchService.ResultsReader.LogLongRunningSearches','Bool','False','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('SearchService.ResultsReader.LongRunningSearchMaxTime','Text','0.0:0:30.000','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('SearchService.ResultsReader.UseRemoteCaching','Bool','False','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('SqlProvider.DefaultLockHint','Text','(nolock)','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('SqlProvider.FetchResultsTimeout','Int','30','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('SqlProvider.MaxDatabaseRows','int','100000','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('TR.Core.LogonDefaultActionName',' Text','Index','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('TR.Core.LogonDefaultActionNamePol','Text','Index','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('TR.Core.LogonDefaultControllerName',' Text','Main','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('ValueMap.MaxHierarchyLevel','Int','7','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('ZugoSearch.ResultSubstringLength','Int','50','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('ZugoSearch.SearchRefreshTimeDisplayInMinutes','Int','5','1') 
INSERT INTO [traderiser].[ConfigurationItem] ([Name],[DataType],[Value],[IsVisible])
  VALUES ('Core.EmailInfoAddress','Text','info@mydomain.com','1') 

