
//var users = [
//          { fullname: 'foo' },
//          { fullname: 'bar' },
//          { fullname: 'twbs' },
//          { fullname: 'eurusd' },
//          { fullname: 'eursek' },
//          { fullname: 'eurjpy' },
//          { fullname: 'eurnok' },
//          { fullname: 'eurnzd' },
//          { fullname: 'eurpln' },
//          { fullname: 'eurpln bullish price changes' },
//          { fullname: 'correlation' },
//          { fullname: 'audcad' },
//          { fullname: 'daily' },
//          { fullname: 'the chfjpy touch the upper Bollinger band in the 1hour timeframe and the last time that the RSI, in the daily timeframe was overbought' },
//          { fullname: 'did the chfjpy touch the upper Bollinger band in the 1hour timeframe and the last time that the RSI, in the daily timeframe was overbought' },
//          { fullname: 'times did the chfjpy touch the upper Bollinger band in the 1hour timeframe and the last time that the RSI, in the daily timeframe was overbought' },
//          { fullname: 'many times did the chfjpy touch the upper Bollinger band in the 1hour timeframe and the last time that the RSI, in the daily timeframe was overbought' },
//          { fullname: 'How many times did the chfjpy touch the upper Bollinger band in the 1hour timeframe and the last time that the RSI, in the daily timeframe was overbought' },
//          { fullname: 'to exhaust or continue in the same direction for a similar movement after gaining/losing 52 pips in a day, between 01/02/2015 to 20/9/2015' },
//          { fullname: 'more likely to exhaust or continue in the same direction for a similar movement after gaining/losing 52 pips in a day, between 01/02/2015 to 20/9/2015' },
//          { fullname: 'Is EUR/CAD more likely to exhaust or continue in the same direction for a similar movement after gaining/losing 52 pips in a day, between 01/02/2015 to 20/9/2015' },
//          { fullname: 'the USD/CAD on the 1h timeframe for the between 21/5/2015 to 10/08/2015' },
//          { fullname: 'for the USD/CAD on the 1h timeframe for the between 21/5/2015 to 10/08/2015' },
//          { fullname: 'trends for the USD/CAD on the 1h timeframe for the between 21/5/2015 to 10/08/2015' },
//          { fullname: 'show trends for the GBP/CAD on the 1h timeframe for the between 21/5/2015 to 10/08/2015' },
//          { fullname: 'show trends on the eurjpy on 1H timeframe for the between 1/5/2015 to 20/08/2015' },
//          { fullname: 'identify bullish price action signals above 20 pips on the eurjpy daily timeframe' },
//          { fullname: 'identify bearish price action signals below 20 pips on the eurpln daily timeframe' },
//          { fullname: 'usdjpy' }
//];


var users = [
{ fullname: '' },
{ fullname: 'adp national employment report' },
{ fullname: 'aig construction index' },
{ fullname: 'aig manufacturing index' },
{ fullname: 'aig services index' },
{ fullname: 'all industries activity index mom' },
{ fullname: 'auto production mom' },
{ fullname: 'average cash earnings yoy' },
{ fullname: 'average earnings index' },
{ fullname: 'average hourly earnings mom' },
{ fullname: 'bank lending mom' },
{ fullname: 'bank of canada monetary policy report' },
{ fullname: 'bank of japan quarterly outlook report' },
{ fullname: 'beige book' },
{ fullname: 'building approvals mom' },
{ fullname: 'building consents mom' },
{ fullname: 'building permits' },
{ fullname: 'building permits mom' },
{ fullname: 'business climate' },
{ fullname: 'business investment qoq' },
{ fullname: 'business nz pmi' },
{ fullname: 'business outlook survey' },
{ fullname: 'business sentiment index' },
{ fullname: 'caged net payroll jobs' },
{ fullname: 'capacity utilization' },
{ fullname: 'capacity utilization mom' },
{ fullname: 'capacity utilization rate' },
{ fullname: 'capex' },
{ fullname: 'capital spending yoy' },
{ fullname: 'cb leading index mom' },
{ fullname: 'cbi industrial trends orders' },
{ fullname: 'chain store sales wow' },
{ fullname: 'chain store sales yoy' },
{ fullname: 'challenger job cuts' },
{ fullname: 'chicago fed national activity' },
{ fullname: 'chicago pmi' },
{ fullname: 'claimant count change' },
{ fullname: 'coincident indicator mom' },
{ fullname: 'commodity prices yoy' },
{ fullname: 'composite pmi' },
{ fullname: 'construction orders yoy' },
{ fullname: 'construction pmi' },
{ fullname: 'construction work done qoq' },
{ fullname: 'consumer confidence' },
{ fullname: 'consumer inflation expectation' },
{ fullname: 'consumer price index index number' },
{ fullname: 'consumer price index mom' },
{ fullname: 'consumer price index qoq' },
{ fullname: 'consumer price index yoy' },
{ fullname: 'continuing jobless claims' },
{ fullname: 'core consumer price index mom' },
{ fullname: 'core consumer price index yoy' },
{ fullname: 'core durable goods orders mom' },
{ fullname: 'core machinery orders mom' },
{ fullname: 'core machinery orders yoy' },
{ fullname: 'core producer price index output mom' },
{ fullname: 'core producer price index output yoy' },
{ fullname: 'core retail price index mom' },
{ fullname: 'core retail price index yoy' },
{ fullname: 'core retail sales mom' },
{ fullname: 'core retail sales qoq' },
{ fullname: 'corporate goods price index mom' },
{ fullname: 'crude oil storage' },
{ fullname: 'cushing crude oil inventories' },
{ fullname: 'debt to gdp ratio' },
{ fullname: 'deposit rate' },
{ fullname: 'durable goods orders mom' },
{ fullname: 'economic bulletin' },
{ fullname: 'economic projections' },
{ fullname: 'electronic card retail sales mom' },
{ fullname: 'empire state manufacturing index' },
{ fullname: 'employment change' },
{ fullname: 'employment change qoq' },
{ fullname: 'existing home sales' },
{ fullname: 'exports yoy' },
{ fullname: 'factory orders mom' },
{ fullname: 'fipe inflation index mom' },
{ fullname: 'fixed asset investment yoy' },
{ fullname: 'fomc statement' },
{ fullname: 'food price index mom' },
{ fullname: 'foreign bonds buying numbers' },
{ fullname: 'foreign direct investment' },
{ fullname: 'foreign exchange flows' },
{ fullname: 'foreign securities purchases' },
{ fullname: 'foreign securities purchases by canadians' },
{ fullname: 'full employment change' },
{ fullname: 'globaldairytrade price index' },
{ fullname: 'gross domestic product annual average' },
{ fullname: 'gross domestic product annualized qoq' },
{ fullname: 'gross domestic product capital expenditure' },
{ fullname: 'gross domestic product chain price index' },
{ fullname: 'gross domestic product expenditure qoq' },
{ fullname: 'gross domestic product final consumption' },
{ fullname: 'gross domestic product mom' },
{ fullname: 'gross domestic product price index yoy' },
{ fullname: 'gross domestic product qoq' },
{ fullname: 'gross domestic product yoy' },
{ fullname: 'halifax house price index mom' },
{ fullname: 'halifax house price index yoy' },
{ fullname: 'hia new home sales mom' },
{ fullname: 'house price index mom' },
{ fullname: 'house price index qoq' },
{ fullname: 'house price index yoy' },
{ fullname: 'house prices yoy' },
{ fullname: 'household spending mom' },
{ fullname: 'household spending yoy' },
{ fullname: 'housing starts' },
{ fullname: 'housing starts mom' },
{ fullname: 'hsbc manufacturing pmi' },
{ fullname: 'import price index mom' },
{ fullname: 'import price index qoq' },
{ fullname: 'imports' },
{ fullname: 'imports yoy' },
{ fullname: 'index of services' },
{ fullname: 'industrial product price index mom' },
{ fullname: 'industrial product price index yoy' },
{ fullname: 'industrial production mom' },
{ fullname: 'industrial production yoy' },
{ fullname: 'industrial sentiment' },
{ fullname: 'inflation expectations qoq' },
{ fullname: 'inflation report' },
{ fullname: 'initial jobless claims' },
{ fullname: 'internet job adverts mom' },
{ fullname: 'ism manufacturing new orders index' },
{ fullname: 'ism manufacturing pmi' },
{ fullname: 'ism non manufacturing pmi' },
{ fullname: 'ism non-manufacturing pmi' },
{ fullname: 'ivey pmi' },
{ fullname: 'job advertisements mom' },
{ fullname: 'jobs applications ratio' },
{ fullname: 'jobseekers total' },
{ fullname: 'kc fed composite index' },
{ fullname: 'labor cost index yoy' },
{ fullname: 'labor productivity qoq' },
{ fullname: 'leading index mom' },
{ fullname: 'long term interest rate' },
{ fullname: 'm3 monetary aggregates' },
{ fullname: 'm3 monetary aggregates yoy' },
{ fullname: 'machine tool orders yoy' },
{ fullname: 'manufacturing pmi' },
{ fullname: 'manufacturing production yoy' },
{ fullname: 'manufacturing sales mom' },
{ fullname: 'manufacturing sales volume qoq' },
{ fullname: 'meeting minutes' },
{ fullname: 'mi leading index mom' },
{ fullname: 'michigan current conditions' },
{ fullname: 'michigan sentiment index' },
{ fullname: 'monetary base yoy' },
{ fullname: 'monetary policy meeting minutes' },
{ fullname: 'monthly report' },
{ fullname: 'national consumer price index yoy' },
{ fullname: 'national core consumer price index yoy' },
{ fullname: 'nationwide hpi mom' },
{ fullname: 'nationwide hpi yoy' },
{ fullname: 'new home sales' },
{ fullname: 'new home sales mom' },
{ fullname: 'new housing price index mom' },
{ fullname: 'new motor vehicle sales mom' },
{ fullname: 'non defense goods orders mom' },
{ fullname: 'non manufacturing pmi' },
{ fullname: 'nonfarm payrolls' },
{ fullname: 'nonfarm productivity qoq' },
{ fullname: 'offshore holdings' },
{ fullname: 'overtime pay yoy' },
{ fullname: 'part time employment change' },
{ fullname: 'participation change' },
{ fullname: 'participation rate' },
{ fullname: 'pending home sales mom' },
{ fullname: 'personal spending mom' },
{ fullname: 'philadelphia fed business conditions' },
{ fullname: 'philadelphia federal reserve manufacturing index' },
{ fullname: 'press conference' },
{ fullname: 'private new capital expenditure qoq' },
{ fullname: 'producer price index input mom' },
{ fullname: 'producer price index input qoq' },
{ fullname: 'producer price index input yoy' },
{ fullname: 'producer price index mom' },
{ fullname: 'producer price index output mom' },
{ fullname: 'producer price index output qoq' },
{ fullname: 'producer price index output yoy' },
{ fullname: 'producer price index yoy' },
{ fullname: 'quantitative easing' },
{ fullname: 'quantitative easing mbs' },
{ fullname: 'quantitative easing total' },
{ fullname: 'quantitative easing treasuries' },
{ fullname: 'raw materials price index mom' },
{ fullname: 'raw materials price index yoy' },
{ fullname: 'rbc manufacturing pmi' },
{ fullname: 'real consumer spending' },
{ fullname: 'real personal consumption mom' },
{ fullname: 'redbook index mom' },
{ fullname: 'redbook index yoy' },
{ fullname: 'requirement ratio' },
{ fullname: 'reserve bank of australia bulletin' },
{ fullname: 'reserve bank of australia financial stability review' },
{ fullname: 'reserve bank of australia statement' },
{ fullname: 'retail pmi' },
{ fullname: 'retail price index mom' },
{ fullname: 'retail price index yoy' },
{ fullname: 'retail sales mom' },
{ fullname: 'retail sales qoq' },
{ fullname: 'retail sales yoy' },
{ fullname: 'richmond manufacturing index' },
{ fullname: 'rics house price balance' },
{ fullname: 'selling price expectations' },
{ fullname: 'services pmi' },
{ fullname: 'small business health index' },
{ fullname: 'tankan big manufacturing outlook index' },
{ fullname: 'tankan large manufacturers index' },
{ fullname: 'tankan large non manufacturers index' },
{ fullname: 'tertiary industry activity index mom' },
{ fullname: 'trade balance non-eu' },
{ fullname: 'trimmed mean consumer price index qoq' },
{ fullname: 'trimmed mean consumer price index yoy' },
{ fullname: 'unemployment rate' },
{ fullname: 'unit labor costs qoq' },
{ fullname: 'visitor arrivals mom' },
{ fullname: 'interest rates' },
{ fullname: 'wage price index qoq' },
{ fullname: 'wage price index yoy' },
{ fullname: 'wholesale price index mom' },
{ fullname: 'wholesale sales mom' },


{ fullname: 'AUDCAD' },
{ fullname: 'AUDCHF' },
{ fullname: 'AUDJPY' },
{ fullname: 'AUDNZD' },
{ fullname: 'AUDUSD' },
{ fullname: 'CADCHF' },
{ fullname: 'CADJPY' },
{ fullname: 'CHFJPY' },
{ fullname: 'CHFNOK' },
{ fullname: 'CHFSEK' },
{ fullname: 'EURAUD' },
{ fullname: 'EURCAD' },
{ fullname: 'EURCHF' },
{ fullname: 'EURCZK' },
{ fullname: 'EURDKK' },
{ fullname: 'EURGBP' },
{ fullname: 'EURHUF' },
{ fullname: 'EURJPY' },
{ fullname: 'EURNOK' },
{ fullname: 'EURNZD' },
{ fullname: 'EURPLN' },
{ fullname: 'EURSEK' },
{ fullname: 'EURTRY' },
{ fullname: 'EURUSD' },
{ fullname: 'GBPAUD' },
{ fullname: 'GBPCAD' },
{ fullname: 'GBPCHF' },
{ fullname: 'GBPJPY' },
{ fullname: 'GBPNZD' },
{ fullname: 'GBPSEK' },
{ fullname: 'GBPUSD' },
{ fullname: 'HKDJPY' },
{ fullname: 'NOKJPY' },
{ fullname: 'NZDCAD' },
{ fullname: 'NZDCHF' },
{ fullname: 'NZDJPY' },
{ fullname: 'NZDUSD' },
{ fullname: 'SEKJPY' },
{ fullname: 'SGDJPY' },
{ fullname: 'TRYJPY' },
{ fullname: 'USDCAD' },
{ fullname: 'USDCHF' },
{ fullname: 'USDCZK' },
{ fullname: 'USDDKK' },
{ fullname: 'USDHKD' },
{ fullname: 'USDHUF' },
{ fullname: 'USDJPY' },
{ fullname: 'USDMXN' },
{ fullname: 'USDNOK' },
{ fullname: 'USDPLN' },
{ fullname: 'USDRUB' },
{ fullname: 'USDSEK' },
{ fullname: 'USDSGD' },
{ fullname: 'USDTRY' },
{ fullname: 'USDZAR' },
{ fullname: 'XAGUSD' },
{ fullname: 'XAUUSD' },
{ fullname: 'ZARJPY' },



{ fullname: 'AUD/CAD' },
{ fullname: 'AUD/CHF' },
{ fullname: 'AUD/JPY' },
{ fullname: 'AUD/NZD' },
{ fullname: 'AUD/USD' },
{ fullname: 'CAD/CHF' },
{ fullname: 'CAD/JPY' },
{ fullname: 'CHF/JPY' },
{ fullname: 'CHF/NOK' },
{ fullname: 'CHF/SEK' },
{ fullname: 'EUR/AUD' },
{ fullname: 'EUR/CAD' },
{ fullname: 'EUR/CHF' },
{ fullname: 'EUR/CZK' },
{ fullname: 'EUR/DKK' },
{ fullname: 'EUR/GBP' },
{ fullname: 'EUR/HUF' },
{ fullname: 'EUR/JPY' },
{ fullname: 'EUR/NOK' },
{ fullname: 'EUR/NZD' },
{ fullname: 'EUR/PLN' },
{ fullname: 'EUR/SEK' },
{ fullname: 'EUR/TRY' },
{ fullname: 'EUR/USD' },
{ fullname: 'GBP/AUD' },
{ fullname: 'GBP/CAD' },
{ fullname: 'GBP/CHF' },
{ fullname: 'GBP/JPY' },
{ fullname: 'GBP/NZD' },
{ fullname: 'GBP/SEK' },
{ fullname: 'GBP/USD' },
{ fullname: 'HKD/JPY' },
{ fullname: 'NOK/JPY' },
{ fullname: 'NZD/CAD' },
{ fullname: 'NZD/CHF' },
{ fullname: 'NZD/JPY' },
{ fullname: 'NZD/USD' },
{ fullname: 'SEK/JPY' },
{ fullname: 'SGD/JPY' },
{ fullname: 'TRY/JPY' },
{ fullname: 'USD/CAD' },
{ fullname: 'USD/CHF' },
{ fullname: 'USD/CZK' },
{ fullname: 'USD/DKK' },
{ fullname: 'USD/HKD' },
{ fullname: 'USD/HUF' },
{ fullname: 'USD/JPY' },
{ fullname: 'USD/MXN' },
{ fullname: 'USD/NOK' },
{ fullname: 'USD/PLN' },
{ fullname: 'USD/RUB' },
{ fullname: 'USD/SEK' },
{ fullname: 'USD/SGD' },
{ fullname: 'USD/TRY' },
{ fullname: 'USD/ZAR' },
{ fullname: 'XAG/USD' },
{ fullname: 'XAU/USD' },
{ fullname: 'ZAR/JPY' },

{ fullname: 'Australia' },
{ fullname: 'Brazil' },
{ fullname: 'Canada' },
{ fullname: 'China' },
{ fullname: 'Euro Zone' },
{ fullname: 'France' },
{ fullname: 'Germany' },
{ fullname: 'Hong Kong' },
{ fullname: 'India' },
{ fullname: 'Italy' },
{ fullname: 'Japan' },
{ fullname: 'New Zealand' },
{ fullname: 'Russia' },
{ fullname: 'Singapore' },
{ fullname: 'South Africa' },
{ fullname: 'South Korea' },
{ fullname: 'Spain' },
{ fullname: 'Switzerland' },
{ fullname: 'United Kingdom' },
{ fullname: 'United States' },
{ fullname: 'UK' },
{ fullname: 'USA' },
{ fullname: 'How many times did the chfjpy touch the upper Bollinger band in the 1hour timeframe and the last time that the RSI, in the daily timeframe was overbought' },
{ fullname: 'Is EUR/CAD more likely to exhaust or continue in the same direction for a similar movement after gaining/losing 52 pips in a day, between 01/02/2015 to 20/9/2015' },
{ fullname: 'Identify bullish price action signals above 20 pips on the eurjpy daily timeframe' },
{ fullname: 'During 2015, how many engulfing patterns on EUR/USD Daily Timeframe resulted in price changes of at least 100 pips?' },
{ fullname: 'In the Daily Charts, whats the correlation between the GBPUSD and the UK interest rates between 20/1/2014 to 23/03/2015?' },
{ fullname: 'Which are the most volatile among the Eur crosses on 15min and 1hour timeframe between 04/04/2015 to 25/05/2015?' },
{ fullname: 'Since 2011, what happens to the us dollar canadian dollar after a rate hike?' },
{ fullname: 'Show bullish price changes above 40 pips on the eurusd' },
{ fullname: 'Highlight the double tops pattern on the usdcad on daily time frame' },
{ fullname: 'Show triangle tops for audusd on the 1hour time frame' },
{ fullname: 'How did the us markets perform last month?' },
{ fullname: 'Which pound crosses are the most bullish on the daily timeframe between 04/04/2015 to 25/04/2015 and was trading above its above 20 simple moving average on daily timeframe for the first time year to date' },
{ fullname: 'Identify when the eurusd has a stochastic below 82 between 01/01/2015 to 30/12/2015' },
{ fullname: 'How has the us gdp qoq been over the last 12 months?' },
{ fullname: 'What is the uk gdp yoy growth?' },
];