//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeRiser.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TradeRiserCoreResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public TradeRiserCoreResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TradeRiser.Core.TradeRiserCoreResource", typeof(TradeRiserCoreResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create user with name &apos;{0}&apos; as a user with that name already exists..
        /// </summary>
        public static string CreateUserAlreadyExists {
            get {
                return ResourceManager.GetString("CreateUserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create user with email address &apos;{0}&apos;.  The email address is already registered against another user..
        /// </summary>
        public static string CreateUserEmailInUse {
            get {
                return ResourceManager.GetString("CreateUserEmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create user with name &apos;{0}&apos; invalid character detected ..
        /// </summary>
        public static string CreateUserInvalidCharacter {
            get {
                return ResourceManager.GetString("CreateUserInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; cannot be empty..
        /// </summary>
        public static string EmptyArgument {
            get {
                return ResourceManager.GetString("EmptyArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified language code is not valid..
        /// </summary>
        public static string InvalidLanguage {
            get {
                return ResourceManager.GetString("InvalidLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified time zone is not valid..
        /// </summary>
        public static string InvalidTimeZone {
            get {
                return ResourceManager.GetString("InvalidTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; of type &apos;{1}&apos; cannot be null..
        /// </summary>
        public static string NullArgument {
            get {
                return ResourceManager.GetString("NullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; cannot be null or empty..
        /// </summary>
        public static string NullOrEmptyArgument {
            get {
                return ResourceManager.GetString("NullOrEmptyArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset and emailed to you..
        /// </summary>
        public static string PasswordResetEmailed {
            get {
                return ResourceManager.GetString("PasswordResetEmailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must meet the following requirements:.
        /// </summary>
        public static string PolicyIntro {
            get {
                return ResourceManager.GetString("PolicyIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - contain at least {0} lowercase character(s).
        /// </summary>
        public static string PolicyLowerChars {
            get {
                return ResourceManager.GetString("PolicyLowerChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - contain at least {0} digit(s).
        /// </summary>
        public static string PolicyMinDigits {
            get {
                return ResourceManager.GetString("PolicyMinDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0} character minimum.
        /// </summary>
        public static string PolicyMinLength {
            get {
                return ResourceManager.GetString("PolicyMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - contain at least {0} uppercase character(s).
        /// </summary>
        public static string PolicyUpperChars {
            get {
                return ResourceManager.GetString("PolicyUpperChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reset the password for user &apos;{0}&apos;.  The user does not exist..
        /// </summary>
        public static string ResetPasswordFailedUnknownUser {
            get {
                return ResourceManager.GetString("ResetPasswordFailedUnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is longer than the allowed length of {1}..
        /// </summary>
        public static string StringTooLong {
            get {
                return ResourceManager.GetString("StringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email message not specified..
        /// </summary>
        public static string ValidateEmailMessage {
            get {
                return ResourceManager.GetString("ValidateEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From address not specified..
        /// </summary>
        public static string ValidateFromAddress {
            get {
                return ResourceManager.GetString("ValidateFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email server address not set..
        /// </summary>
        public static string ValidateServer {
            get {
                return ResourceManager.GetString("ValidateServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject not specified..
        /// </summary>
        public static string ValidateSubject {
            get {
                return ResourceManager.GetString("ValidateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To address not specified..
        /// </summary>
        public static string ValidateToAddress {
            get {
                return ResourceManager.GetString("ValidateToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty..
        /// </summary>
        public static string ValueCannotBeEmpty {
            get {
                return ResourceManager.GetString("ValueCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null..
        /// </summary>
        public static string ValueCannotBeNull {
            get {
                return ResourceManager.GetString("ValueCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value exceeds {0} characters..
        /// </summary>
        public static string ValueExceedsLength {
            get {
                return ResourceManager.GetString("ValueExceedsLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value does not match against the regular expression..
        /// </summary>
        public static string ValueNoRegexMatch {
            get {
                return ResourceManager.GetString("ValueNoRegexMatch", resourceCulture);
            }
        }
    }
}
